# .github/workflows/use-environment.yml
name: Use Environment Variables

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  use-environment:
    name: Use Environment Variables
    runs-on: ubuntu-latest

    environment:
      name: environmentone # Link the workflow to 'environmentone'

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Display and use environment variables
      - name: Check environment variables
        run: |
          if [[ -n "$EMPLOYEEID" && -n "$EMAILID" ]]; then
            echo "Processing employee with ID $EMPLOYEEID and email $EMAILID"
          else
            echo "Missing required environment variables"
            exit 1
          fi
        shell: bash
        env:
          EMPLOYEEID: ${{ vars.EMPLOYEEID }}
          EMAILID: ${{ vars.EMAILID }}
