name: script file Processing Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  file-processing:
    runs-on: ubuntu-latest
    env:
      FILE1: file1.txt
      FILE2: file2.txt
      OUTPUT_FILE: output.txt

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug file paths
      - name: Debug file paths
        run: |
          echo "Listing root directory contents:"
          ls -la
          echo "Listing scripts directory contents:"
          ls -la scripts

      # Make scripts executable
      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      # List files using script
      - name: List files in the repository
        run: ./scripts/list-files.sh

      # Process files using script
      - name: Read and process files
        run: ./scripts/process-files.sh

      # Save the new file as an artifact
      - name: Upload output.txt as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: output.txt
