name: script File Processing Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  file-processing:
    runs-on: ubuntu-latest
    env:
      # Define variables
      FILE1: file1.txt
      FILE2: file2.txt
      OUTPUT_FILE: output.txt

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # List files using script
      - name: List files in the repository
        run: ./scripts/list-files.sh
      
      # Process files using script
      - name: Read and process files
        run: ./scripts/process-files.sh
      
      # Save the new file as an artifact
      - name: Upload combined file
        uses: actions/upload-artifact@v3
        with:
          name: combined-file
          path: ${{ env.OUTPUT_FILE }}
